from rest_framework import serializers
from .models import User, Job, Application, Resume

# ============================================================
# USER SERIALIZER
# ============================================================

class UserSerializer(serializers.ModelSerializer):
    """Serialize basic user info."""
    
    class Meta:
        model = User
        fields = ['id', 'username', 'email', 'role']
        read_only_fields = ['id', 'role']


# ============================================================
# JOB SERIALIZERS
# ============================================================

class JobSerializer(serializers.ModelSerializer):
    """Serialize job details with nested employer info."""
    
    employer = UserSerializer(read_only=True)

    class Meta:
        model = Job
        fields = [
            'id',
            'employer',
            'title',
            'description',
            'location',
            'duration',
            'skills',
            'approved',
            'created_at',
        ]
        read_only_fields = ['id', 'employer', 'approved', 'created_at']


class JobCreateSerializer(serializers.ModelSerializer):
    """Serializer for creating/updating jobs (employer only)."""
    
    class Meta:
        model = Job
        fields = ['title', 'description', 'location', 'duration', 'skills']
        extra_kwargs = {
            'title': {'required': True},
            'description': {'required': True},
            'location': {'required': True},
            'duration': {'required': True},
            'skills': {'required': False},
        }


# ============================================================
# APPLICATION SERIALIZER
# ============================================================

class ApplicationSerializer(serializers.ModelSerializer):
    """Serialize application with nested student and job info."""
    
    job = JobSerializer(read_only=True)
    student = UserSerializer(read_only=True)

    class Meta:
        model = Application
        fields = [
            'id',
            'job',
            'student',
            'status',        # employer can update
            'match_score',   # read-only generated score
            'created_at',
        ]
        read_only_fields = ['id', 'job', 'student', 'match_score', 'created_at']


# ============================================================
# RESUME SERIALIZER
# ============================================================

class ResumeSerializer(serializers.ModelSerializer):
    """Serialize resume with nested student info and autogenerated fields."""
    
    student = UserSerializer(read_only=True)

    class Meta:
        model = Resume
        fields = [
            'id',
            'student',
            'file',
            'resume_score',
            'feedback',
            'uploaded_at',
        ]
        read_only_fields = ['id', 'student', 'resume_score', 'feedback', 'uploaded_at']
